name: Release Helm Chart to OCI

on:
  push:
    branches: [ main ]
    paths:
      - 'helm/**'
  release:
    types: [ published ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  CHART_NAME: kua-auth

jobs:
  release-oci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm Chart
        run: |
          helm package helm/${{ env.CHART_NAME }}

      - name: Push Chart to OCI Registry
        run: |
          helm push ${{ env.CHART_NAME }}-*.tgz oci://${{ env.REGISTRY }}/${{ github.repository_owner }}

      - name: Generate Summary
        run: |
          echo "## 📦 Helm Chart Published Successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### OCI Registry" >> $GITHUB_STEP_SUMMARY
          echo "- **Registry:** \`${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.CHART_NAME }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installation Commands" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "# Install from OCI registry" >> $GITHUB_STEP_SUMMARY
          echo "helm install ${{ env.CHART_NAME }} oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.CHART_NAME }} \\" >> $GITHUB_STEP_SUMMARY
          echo "  --namespace ${{ env.CHART_NAME }} \\" >> $GITHUB_STEP_SUMMARY
          echo "  --create-namespace" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Or from Helm repository" >> $GITHUB_STEP_SUMMARY
          echo "helm repo add ${{ env.CHART_NAME }} https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}" >> $GITHUB_STEP_SUMMARY
          echo "helm install ${{ env.CHART_NAME }} ${{ env.CHART_NAME }}/${{ env.CHART_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY 