{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-user-admin.fullname" . }}-backend
  labels:
    {{- include "kube-user-admin.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.name }}
      protocol: TCP
      name: {{ .Values.backend.service.name }}
  selector:
    {{- include "kube-user-admin.backend.selectorLabels" . | nindent 4 }}
{{- end }} 